Repository IBM/javacore-analyser, pull requests merged in 2024-11, with the labels that each got.

#23 8 generate web application
  CONTRIBUTING.md
  README.md
  constants.py
  javacore_analyser_web.py
  javacore_analyzer.py
  javacore_set.py
  logging_utils.py
  requirements.txt
  templates/index.html
Labels: enhancement, current sprint (22.11)

#35 34 adding closing tag should be set with debug level
  verbose_gc.py
Labels: bug, good first issue

#33 Fix #28 Simplify web
  templates/index.html
Labels: good first issue

#45 18-GC-activity-chart-shows-wrong-values-when-xmx-has-no-units
  data/jquery/wait2scripts.js
Labels: bug

#15 Fixes #14 Implemented progressbars
  javacore_set.py
  requirements.txt
Labels: enhancement, good first issue, current sprint (22.11)

#37 12 generate pip package
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  README.md
  pyproject.toml
  requirements.txt
  src/javacore_analyser/__init__.py
  src/javacore_analyser/abstract_snapshot_collection.py
  src/javacore_analyser/code_snapshot_collection.py
  src/javacore_analyser/constants.py
  src/javacore_analyser/data/expand.js
  src/javacore_analyser/data/jquery/chart.js
  src/javacore_analyser/data/jquery/chartjs-adapter-date-fns.bundle.min.js
  src/javacore_analyser/data/jquery/jq.css
  src/javacore_analyser/data/jquery/jquery.mark.min.js
  src/javacore_analyser/data/jquery/jquery.min.js
  src/javacore_analyser/data/jquery/jquery.tablesorter.min.js
  src/javacore_analyser/data/jquery/jquery.tablesorter.widgets.min.js
  src/javacore_analyser/data/jquery/search.js
  src/javacore_analyser/data/jquery/sorting.js
  src/javacore_analyser/data/jquery/theme.blue.css
  src/javacore_analyser/data/jquery/theme.default.min.css
  src/javacore_analyser/data/jquery/wait2scripts.js
  src/javacore_analyser/data/style.css
  src/javacore_analyser/data/xml/index.xml
  src/javacore_analyser/data/xml/javacores/javacore.xml
  src/javacore_analyser/data/xml/javacores/javacore.xsl
  src/javacore_analyser/data/xml/report.xsl
  src/javacore_analyser/data/xml/threads/thread.xml
  src/javacore_analyser/data/xml/threads/thread.xsl
  src/javacore_analyser/java_thread.py
  src/javacore_analyser/javacore.py
  src/javacore_analyser/javacore_analyser_batch.py
  src/javacore_analyser/javacore_analyser_web.py
  src/javacore_analyser/javacore_set.py
  src/javacore_analyser/logging_utils.py
  src/javacore_analyser/snapshot_collection.py
  src/javacore_analyser/snapshot_collection_collection.py
  src/javacore_analyser/stack_trace.py
  src/javacore_analyser/stack_trace_element.py
  src/javacore_analyser/stack_trace_kind.py
  src/javacore_analyser/templates/index.html
  src/javacore_analyser/thread_snapshot.py
  src/javacore_analyser/tips.py
  src/javacore_analyser/verbose_gc.py
  test/test_code_snapshot_collection.py
  test/test_gc_collection.py
  test/test_java_thread.py
  test/test_javacore.py
  test/test_javacore_analyser.py
  test/test_javacore_set.py
  test/test_stack_trace.py
  test/test_stack_trace_element.py
  test/test_thread_snapshot.py
  test/test_tips.py
  test/test_verbose_gc_parser.py
Labels: enhancement

#56 Tidied up the expensive operation message
  src/javacore_analyser/templates/index.html
Labels: good first issue

#54 Switched the doc link to point to the public wiki on github
  src/javacore_analyser/data/xml/report.xsl
Labels: good first issue

#51 Added search bar to thread.xsl and javacore.xsl
  src/javacore_analyser/data/xml/javacores/javacore.xsl
  src/javacore_analyser/data/xml/threads/thread.xsl
Labels: good first issue
