Repository IBM/javacore-analyser, pull requests merged in 2025-05, with the labels that each got.

#145 #144 Add documentation for few methods.
  src/javacore_analyser/javacore_analyser_batch.py
  src/javacore_analyser/javacore_analyser_web.py
Labels: task

#148 142 treat any thread with a truncated stack as interesting
  src/javacore_analyser/java_thread.py
  src/javacore_analyser/stack_trace.py
  test/test_java_thread.py
Labels: enhancement

#155 #154 Generate pip package for all branches
  .travis.yml
Labels: bug
