Repository IBM/javacore-analyser, pull requests merged in 2025-01, with the labels that each got.

#89 Add har file support
  pyproject.toml
  requirements.txt
  src/javacore_analyser/data/jquery/theme.blue.css
  src/javacore_analyser/data/style.css
  src/javacore_analyser/data/xml/report.xsl
  src/javacore_analyser/har_file.py
  src/javacore_analyser/javacore_set.py
  test/data/javacores/jazz.net_Archive [25-01-03 11-07-56].har
  test/test_har_file.py
Labels: enhancement

#88 87-better-logging-when-processing-is-failing
  src/javacore_analyser/data/html/error.html
  src/javacore_analyser/javacore_analyser_batch.py
  test/test_javacore_analyser.py
Labels: enhancement, good first issue

#102 Fixes #101 - improve the message regarding generating placeholder htmls
  src/javacore_analyser/javacore_set.py
Labels: enhancement, good first issue

#82 Create release in github
  .travis.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
Labels: enhancement

#100 Fixes #99 do not include test dir to source package for pip
  pyproject.toml
Labels: enhancement

#104 Fixes #103 run builds on Main branch
  .travis.yml
Labels: bug, good first issue

#84 #47 Create official container image
  CONTRIBUTING.md
  Dockerfile
  README.md
Labels: documentation

#77 #61 Adopt env properties for dockerfile
  Dockerfile
  README.md
Labels: good first issue

#108 #107 Improve performance of processing verbose gc files.
  src/javacore_analyser/verbose_gc.py
  test/data/javacores/verbosegc.230420.33424.txt.001
Labels: enhancement

#112 #111 Pass tool version to dockerfile
  CONTRIBUTING.md
  Dockerfile
Labels: enhancement, good first issue

#118 Fixes #117 Add brackets to ARG in Dockerfile
  Dockerfile
Labels: good first issue
